name: Script Workflow (Lint, Security, Test. Env)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    env:
      REQUIRED_VAR: "workflow_value"

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Ensure script is executable
        run: chmod +x scripts/my-script.sh

      - name: Show test message
        run: echo "Running simple test assertion..."

      - name: Execute Test Script
        run: ./scripts/my-script.sh

      - name: Install ShellCheck (Linter)
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck on the Script
        run: shellcheck scripts/my-script.sh

      - name: Install Flawfiner (SAST Tool)
        run: sudo apt-get install -y flawfinder

      - name: Run Flawfinder security scan on script
        run: flawfinder scripts/my-script.sh
